# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### Update meal
#### curl -v -X "PUT" -H "Content-Type: application/json" -d '{ "dateTime": "2015-05-30T11:00:00", "description": "breacfast", "calories": 1500}' http://localhost:8080/topjava/rest/meals/100002
PUT http://localhost:8080/topjava/rest/meals/100002
Content-Type: application/json

 {

    "dateTime": "2015-05-30T11:00:00",
    "description": "Поздний Завтрак",
    "calories": 1500

  }

###